{
 "title": "Dashboard Template",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Client", "label": "Client", "query": "DT" },
   {
    "name": "binsize",
    "label": "Interval",
    "query": "1m,5m,15m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Incomming API Gateway | DT", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "TPS | $Client",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "TPS" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "AzureDiagnostics\r\n| where $__timeFilter( TimeGenerated)\r\n| extend Client = case(\r\n    productId_s == \"product-prd-dt\", \"DT\",\r\n    \"other\"\r\n)\r\n| where Client == \"DT\"\r\n| where apiId_s in (\"ext-api-sales-bff-px\", \"ext-api-sap-px\")\r\n| where operationId_s in (\"cancelShoppingCart\", \"reserveProductStock\", \"0186-serialNumberValidation\", \"0337-createQueryStockNonSerial\")\r\n| extend class = strcat(Client, \" | \", apiId_s, \" | \", operationId_s)\r\n| summarize TPS1S = count() by bin(TimeGenerated,1s), tostring(class)\r\n| summarize TPS = max(TPS1S) by bin(TimeGenerated,$binsize), tostring(class)\r\n| order by TimeGenerated asc\r\n| render timechart ",
      "resources": [
       "/subscriptions/43eb09a8-038e-46d9-9a1f-dcefeed0376c/resourceGroups/rg-dsbcommon-az-asse-prd-001/providers/Microsoft.ApiManagement/service/apim-dsbcommon-az-asse-prd-001"
      ],
      "resultFormat": "time_series"
     }
    }
   ]
  },
  {
   "title": "Response Time | $Client",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "AzureDiagnostics\r\n| where $__timeFilter( TimeGenerated)\r\n| extend Client = case(\r\n    productId_s == \"product-prd-dt\", \"DT\",\r\n    \"other\"\r\n)\r\n| where Client == \"DT\"\r\n| where apiId_s in (\"ext-api-sales-bff-px\", \"ext-api-sap-px\")\r\n| where operationId_s in (\"cancelShoppingCart\", \"reserveProductStock\", \"0186-serialNumberValidation\", \"0337-createQueryStockNonSerial\")\r\n| extend class = strcat(Client, \" | \", apiId_s, \" | \", operationId_s)\r\n| extend class = strcat(Client, \" | \", apiId_s, \" | \", operationId_s)\r\n| summarize percentiles(DurationMs,99) by bin(TimeGenerated,$binsize), tostring(class)\r\n| order by TimeGenerated asc  \r\n| render timechart",
      "resources": [
       "/subscriptions/43eb09a8-038e-46d9-9a1f-dcefeed0376c/resourceGroups/rg-dsbcommon-az-asse-prd-001/providers/Microsoft.ApiManagement/service/apim-dsbcommon-az-asse-prd-001"
      ],
      "resultFormat": "time_series"
     }
    }
   ]
  },
  {
   "title": "Error | $Client",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "AzureDiagnostics\r\n| where $__timeFilter( TimeGenerated)\r\n| extend Client = case(\r\n    productId_s == \"product-prd-dt\", \"DT\",\r\n    \"other\"\r\n)\r\n| where Client == \"DT\"\r\n| where apiId_s in (\"ext-api-sales-bff-px\", \"ext-api-sap-px\")\r\n| where operationId_s in (\"cancelShoppingCart\", \"reserveProductStock\", \"0186-serialNumberValidation\", \"0337-createQueryStockNonSerial\")\r\n| extend class = strcat(Client, \" | \", apiId_s, \" | \", operationId_s)\r\n| where responseCode_d !between (200 .. 399) \r\n| extend class = strcat(Client, \" | \", apiId_s, \" | \", operationId_s, \" | \",responseCode_d)\r\n| summarize count() by bin(TimeGenerated,$binsize), tostring(class)\r\n| order by TimeGenerated asc\r\n| render timechart ",
      "resources": [
       "/subscriptions/43eb09a8-038e-46d9-9a1f-dcefeed0376c/resourceGroups/rg-dsbcommon-az-asse-prd-001/providers/Microsoft.ApiManagement/service/apim-dsbcommon-az-asse-prd-001"
      ],
      "resultFormat": "time_series"
     }
    }
   ]
  },
  {
   "title": "Transactions | $Client",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "AzureDiagnostics\r\n| where $__timeFilter( TimeGenerated)\r\n| extend Client = case(\r\n    productId_s == \"product-prd-dt\", \"DT\",\r\n    \"other\"\r\n)\r\n| where Client == \"DT\"\r\n| where apiId_s in (\"ext-api-sales-bff-px\", \"ext-api-sap-px\")\r\n| where operationId_s in (\"cancelShoppingCart\", \"reserveProductStock\", \"0186-serialNumberValidation\", \"0337-createQueryStockNonSerial\")\r\n| extend class = strcat(Client, \" | \", apiId_s, \" | \", operationId_s)\r\n| summarize count() by bin(TimeGenerated,$binsize), tostring(class)\r\n| order by TimeGenerated asc\r\n| render timechart ",
      "resources": [
       "/subscriptions/43eb09a8-038e-46d9-9a1f-dcefeed0376c/resourceGroups/rg-dsbcommon-az-asse-prd-001/providers/Microsoft.ApiManagement/service/apim-dsbcommon-az-asse-prd-001"
      ],
      "resultFormat": "time_series"
     }
    }
   ]
  },
  {
   "title": "SUCCESS_RATE",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "AzureDiagnostics\r\n| where $__timeFilter( TimeGenerated)\r\n| extend Client = case(\r\n    productId_s == \"product-prd-dt\", \"DT\",\r\n    \"other\"\r\n)\r\n| where Client == \"DT\"\r\n| where apiId_s in (\"ext-api-sales-bff-px\", \"ext-api-sap-px\")\r\n| where operationId_s in (\"cancelShoppingCart\", \"reserveProductStock\", \"0186-serialNumberValidation\", \"0337-createQueryStockNonSerial\")\r\n| extend class = strcat(Client, \" | \", apiId_s, \" | \", operationId_s)\r\n| extend class = strcat(Client, \" | \", apiId_s, \" | \", operationId_s)\r\n| extend Code = case(\r\n         responseCode_d between (200 .. 399) or responseCode_d == 404, \"success\",\r\n         \"Other\")\r\n| summarize TotalCount = count(), \r\n            Countsuccess = countif(Code == \"success\") by bin(TimeGenerated, $binsize) , class\r\n| extend SuccessRate = todouble(Countsuccess) * 100.0 / TotalCount\r\n| project TimeGenerated , SuccessRate , class\r\n| order by TimeGenerated asc  \r\n| render timechart",
      "resources": [
       "/subscriptions/43eb09a8-038e-46d9-9a1f-dcefeed0376c/resourceGroups/rg-dsbcommon-az-asse-prd-001/providers/Microsoft.ApiManagement/service/apim-dsbcommon-az-asse-prd-001"
      ],
      "resultFormat": "time_series"
     }
    }
   ]
  },
  { "title": "Outgoing API Gateway | $Client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "SUCCESS_RATE",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "AzureDiagnostics\r\n| where $__timeFilter( TimeGenerated)\r\n| where isnotempty(backendResponseCode_d)\r\n| extend Client = case(\r\n    productId_s == \"product-prd-dt\", \"DT\",\r\n    \"other\"\r\n)\r\n| where Client == \"DT\"\r\n| where apiId_s in (\"ext-api-sales-bff-px\", \"ext-api-sap-px\")\r\n| where operationId_s in (\"cancelShoppingCart\", \"reserveProductStock\", \"0186-serialNumberValidation\", \"0337-createQueryStockNonSerial\")\r\n| extend class = strcat(Client, \" | \", apiId_s, \" | \", operationId_s)\r\n| extend Code = case(\r\n         responseCode_d between (200 .. 399) or responseCode_d == 404, \"success\",\r\n         \"Other\")\r\n| summarize TotalCount = count(), \r\n            Countsuccess = countif(Code == \"success\") by bin(TimeGenerated, $binsize) , class\r\n| extend SuccessRate = todouble(Countsuccess) * 100.0 / TotalCount\r\n| project TimeGenerated , SuccessRate , class\r\n| order by TimeGenerated asc  \r\n| render timechart",
      "resources": [
       "/subscriptions/43eb09a8-038e-46d9-9a1f-dcefeed0376c/resourceGroups/rg-dsbcommon-az-asse-prd-001/providers/Microsoft.ApiManagement/service/apim-dsbcommon-az-asse-prd-001"
      ],
      "resultFormat": "time_series"
     }
    }
   ]
  },
  {
   "title": "TPS | $Client",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "TPS" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "AzureDiagnostics\r\n| where $__timeFilter( TimeGenerated)\r\n| where isnotempty(backendResponseCode_d)\r\n| extend Client = case(\r\n    productId_s == \"product-prd-dt\", \"DT\",\r\n    \"other\"\r\n)\r\n| where Client == \"DT\"\r\n| where apiId_s in (\"ext-api-sales-bff-px\", \"ext-api-sap-px\")\r\n| where operationId_s in (\"cancelShoppingCart\", \"reserveProductStock\", \"0186-serialNumberValidation\", \"0337-createQueryStockNonSerial\")\r\n| extend class = strcat(Client, \" | \", apiId_s, \" | \", operationId_s)\r\n| extend class = strcat(Client, \" | \", apiId_s, \" | \", operationId_s)\r\n| summarize TPS1S = count() by bin(TimeGenerated,1s), tostring(class)\r\n| summarize TPS = max(TPS1S) by bin(TimeGenerated,$binsize), tostring(class)\r\n| order by TimeGenerated asc\r\n| render timechart ",
      "resources": [
       "/subscriptions/43eb09a8-038e-46d9-9a1f-dcefeed0376c/resourceGroups/rg-dsbcommon-az-asse-prd-001/providers/Microsoft.ApiManagement/service/apim-dsbcommon-az-asse-prd-001"
      ],
      "resultFormat": "time_series"
     }
    }
   ]
  },
  {
   "title": "Transactions | $Client",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "AzureDiagnostics\r\n| where $__timeFilter( TimeGenerated)\r\n| extend Client = case(\r\n    productId_s == \"product-prd-dt\", \"DT\",\r\n    \"other\"\r\n)\r\n| where Client == \"DT\"\r\n| where apiId_s in (\"ext-api-sales-bff-px\", \"ext-api-sap-px\")\r\n| where operationId_s in (\"cancelShoppingCart\", \"reserveProductStock\", \"0186-serialNumberValidation\", \"0337-createQueryStockNonSerial\")\r\n| extend class = strcat(Client, \" | \", apiId_s, \" | \", operationId_s)\r\n| summarize count() by bin(TimeGenerated,$binsize), tostring(class)\r\n| order by TimeGenerated asc\r\n| render timechart ",
      "resources": [
       "/subscriptions/43eb09a8-038e-46d9-9a1f-dcefeed0376c/resourceGroups/rg-dsbcommon-az-asse-prd-001/providers/Microsoft.ApiManagement/service/apim-dsbcommon-az-asse-prd-001"
      ],
      "resultFormat": "time_series"
     }
    }
   ]
  },
  {
   "title": "Response Time | $Client",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "AzureDiagnostics\r\n| where $__timeFilter( TimeGenerated)\r\n| where isnotempty(backendResponseCode_d)\r\n| extend Client = case(\r\n    productId_s == \"product-prd-dt\", \"DT\",\r\n    \"other\"\r\n)\r\n| where Client == \"DT\"\r\n| where apiId_s in (\"ext-api-sales-bff-px\", \"ext-api-sap-px\")\r\n| where operationId_s in (\"cancelShoppingCart\", \"reserveProductStock\", \"0186-serialNumberValidation\", \"0337-createQueryStockNonSerial\")\r\n| extend class = strcat(Client, \" | \", apiId_s, \" | \", operationId_s)\r\n| summarize percentiles(backendTime_d,99) by bin(TimeGenerated,$binsize), tostring(class)\r\n| order by TimeGenerated asc  \r\n| render timechart",
      "resources": [
       "/subscriptions/43eb09a8-038e-46d9-9a1f-dcefeed0376c/resourceGroups/rg-dsbcommon-az-asse-prd-001/providers/Microsoft.ApiManagement/service/apim-dsbcommon-az-asse-prd-001"
      ],
      "resultFormat": "time_series"
     }
    }
   ]
  },
  {
   "title": "Error | $Client",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "AzureDiagnostics\r\n| where $__timeFilter( TimeGenerated)\r\n| where isnotempty(backendResponseCode_d)\r\n| extend Client = case(\r\n    productId_s == \"product-prd-dt\", \"DT\",\r\n    \"other\"\r\n)\r\n| where Client == \"DT\"\r\n| where apiId_s in (\"ext-api-sales-bff-px\", \"ext-api-sap-px\")\r\n| where operationId_s in (\"cancelShoppingCart\", \"reserveProductStock\", \"0186-serialNumberValidation\", \"0337-createQueryStockNonSerial\")\r\n| extend class = strcat(Client, \" | \", apiId_s, \" | \", operationId_s)\r\n| where responseCode_d !between (200 .. 399)\r\n| extend class = strcat(Client, \" | \", apiId_s, \" | \", operationId_s, \" | \",responseCode_d)\r\n| summarize count() by bin(TimeGenerated,$binsize), tostring(class)\r\n| order by TimeGenerated asc\r\n| render timechart ",
      "resources": [
       "/subscriptions/43eb09a8-038e-46d9-9a1f-dcefeed0376c/resourceGroups/rg-dsbcommon-az-asse-prd-001/providers/Microsoft.ApiManagement/service/apim-dsbcommon-az-asse-prd-001"
      ],
      "resultFormat": "time_series"
     }
    }
   ]
  }
 ]
}