{
 "title": "{{PROJECT_UPPER}} | {{env_upper}} | API Gateway",
 "tags": [
  "{{env}}",
  "project-{{project}}",
  "auto-generated"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Client", "label": "Client", "query": "{{PROJECT_UPPER}}" },
   { "name": "binsize", "label": "Interval", "query": "1m,5m,15m,30m,1h,6h,12h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Incomming API Gateway | {{PROJECT_UPPER}}",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "TPS | $Client",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "TPS" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "AzureDiagnostics\r\n| where $__timeFilter( TimeGenerated)\r\n| extend Client = case(\r\n    productId_s == \"{{product}}\", \"{{PROJECT_UPPER}}\",\r\n    \"other\"\r\n)\r\n| where Client == \"{{PROJECT_UPPER}}\"\r\n| where apiId_s in ({{APIS_KQL_LIST}})\r\n| where operationId_s in ({{OPERATIONS_KQL_LIST}})\r\n| extend class = strcat(Client, \" | \", apiId_s, \" | \", operationId_s)\r\n| summarize TPS1S = count() by bin(TimeGenerated,1s), tostring(class)\r\n| summarize TPS = max(TPS1S) by bin(TimeGenerated,{{binsize}}), tostring(class)\r\n| order by TimeGenerated asc\r\n| render timechart ",
      "resources": [ "{{AZURE_RESOURCE}}" ],
      "resultFormat": "time_series"
     }
    }
   ]
  },
  {
   "title": "Response Time (p99) | $Client",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "AzureDiagnostics\r\n| where $__timeFilter( TimeGenerated)\r\n| extend Client = case(\r\n    productId_s == \"{{product}}\", \"{{PROJECT_UPPER}}\",\r\n    \"other\"\r\n)\r\n| where Client == \"{{PROJECT_UPPER}}\"\r\n| where apiId_s in ({{APIS_KQL_LIST}})\r\n| where operationId_s in ({{OPERATIONS_KQL_LIST}})\r\n| extend class = strcat(Client, \" | \", apiId_s, \" | \", operationId_s)\r\n| summarize percentiles(DurationMs,99) by bin(TimeGenerated,{{binsize}}), tostring(class)\r\n| order by TimeGenerated asc  \r\n| render timechart",
      "resources": [ "{{AZURE_RESOURCE}}" ],
      "resultFormat": "time_series"
     }
    }
   ]
  },
  {
   "title": "Transactions | $Client",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "AzureDiagnostics\r\n| where $__timeFilter( TimeGenerated)\r\n| extend Client = case(\r\n    productId_s == \"{{product}}\", \"{{PROJECT_UPPER}}\",\r\n    \"other\"\r\n)\r\n| where Client == \"{{PROJECT_UPPER}}\"\r\n| where apiId_s in ({{APIS_KQL_LIST}})\r\n| where operationId_s in ({{OPERATIONS_KQL_LIST}})\r\n| extend class = strcat(Client, \" | \", apiId_s, \" | \", operationId_s)\r\n| summarize count() by bin(TimeGenerated,{{binsize}}), tostring(class)\r\n| order by TimeGenerated asc\r\n| render timechart ",
      "resources": [ "{{AZURE_RESOURCE}}" ],
      "resultFormat": "time_series"
     }
    }
   ]
  },
  {
   "title": "Error (4xx/5xx) | $Client",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "AzureDiagnostics\r\n| where $__timeFilter( TimeGenerated)\r\n| extend Client = case(\r\n    productId_s == \"{{product}}\", \"{{PROJECT_UPPER}}\",\r\n    \"other\"\r\n)\r\n| where Client == \"{{PROJECT_UPPER}}\"\r\n| where apiId_s in ({{APIS_KQL_LIST}})\r\n| where operationId_s in ({{OPERATIONS_KQL_LIST}})\r\n| extend class = strcat(Client, \" | \", apiId_s, \" | \", operationId_s)\r\n| where responseCode_d !between (200 .. 399) \r\n| extend class = strcat(Client, \" | \", apiId_s, \" | \", operationId_s, \" | \",responseCode_d)\r\n| summarize count() by bin(TimeGenerated,{{binsize}}), tostring(class)\r\n| order by TimeGenerated asc\r\n| render timechart ",
      "resources": [ "{{AZURE_RESOURCE}}" ],
      "resultFormat": "time_series"
     }
    }
   ]
  },
  { "title": "Backend | {{PROJECT_UPPER}}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Backend Response Time (p99) | $Client",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "AzureDiagnostics\r\n| where $__timeFilter( TimeGenerated)\r\n| where isnotempty(backendResponseCode_d)\r\n| extend Client = case(\r\n    productId_s == \"{{product}}\", \"{{PROJECT_UPPER}}\",\r\n    \"other\"\r\n)\r\n| where Client == \"{{PROJECT_UPPER}}\"\r\n| where apiId_s in ({{APIS_KQL_LIST}})\r\n| where operationId_s in ({{OPERATIONS_KQL_LIST}})\r\n| extend class = strcat(Client, \" | \", apiId_s, \" | \", operationId_s)\r\n| summarize percentiles(backendTime_d,99) by bin(TimeGenerated,{{binsize}}), tostring(class)\r\n| order by TimeGenerated asc  \r\n| render timechart",
      "resources": [ "{{AZURE_RESOURCE}}" ],
      "resultFormat": "time_series"
     }
    }
   ]
  },
  {
   "title": "Backend Error | $Client",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "azureLogAnalytics": {
      "dashboardTime": false,
      "query": "AzureDiagnostics\r\n| where $__timeFilter( TimeGenerated)\r\n| where isnotempty(backendResponseCode_d)\r\n| extend Client = case(\r\n    productId_s == \"{{product}}\", \"{{PROJECT_UPPER}}\",\r\n    \"other\"\r\n)\r\n| where Client == \"{{PROJECT_UPPER}}\"\r\n| where apiId_s in ({{APIS_KQL_LIST}})\r\n| where operationId_s in ({{OPERATIONS_KQL_LIST}})\r\n| extend class = strcat(Client, \" | \", apiId_s, \" | \", operationId_s)\r\n| where responseCode_d !between (200 .. 399)\r\n| extend class = strcat(Client, \" | \", apiId_s, \" | \", operationId_s, \" | \",responseCode_d)\r\n| summarize count() by bin(TimeGenerated,{{binsize}}), tostring(class)\r\n| order by TimeGenerated asc\r\n| render timechart ",
      "resources": [ "{{AZURE_RESOURCE}}" ],
      "resultFormat": "time_series"
     }
    }
   ]
  }
 ]
}